# Generated by Django 4.2.3 on 2024-03-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main_setting', models.BooleanField(verbose_name='تنظیمات اصلی/غیر اصلی')),
                ('site_name', models.CharField(max_length=200, verbose_name='نام نمایشی سایت')),
                ('site_url', models.CharField(max_length=255, verbose_name='آدرس سایت')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='تلفن')),
                ('fax', models.CharField(blank=True, max_length=200, null=True, verbose_name='فکس')),
                ('email', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس ایمیل')),
                ('copyright_text', models.TextField(max_length=200, verbose_name='متن کپی رایت')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
                ('about_us_text', models.TextField(verbose_name='متن درباره ما')),
                ('site_logo', models.ImageField(upload_to='admin-uploads/user-uploads', verbose_name='تصویر سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'کلیه تنظیمات',
            },
        ),
    ]
