# Generated by Django 4.2.3 on 2024-03-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام برنامه')),
                ('url', models.CharField(max_length=255, verbose_name='لینک برنامه')),
                ('logo', models.ImageField(upload_to='admin-uploads/logos', verbose_name='لوگو برنامه')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='social_medias',
            field=models.ManyToManyField(blank=True, null=True, to='site_module.socialmedias', verbose_name='شبکه های اجتماعی'),
        ),
    ]
