# Generated by Django 4.2.3 on 2024-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0002_socialmedias_sitesetting_social_medias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='social_medias',
            field=models.ManyToManyField(blank=True, to='site_module.socialmedias', verbose_name='شبکه های اجتماعی'),
        ),
    ]
