# Generated by Django 4.2.3 on 2024-03-22 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0003_alter_sitesetting_social_medias'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterBoxHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام')),
            ],
            options={
                'verbose_name': 'سرتیتر',
                'verbose_name_plural': 'سرتیتر ها',
            },
        ),
        migrations.CreateModel(
            name='FooterBoxItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='نام آیتم')),
                ('url', models.CharField(max_length=300, verbose_name='لینک')),
                ('footer_box_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='site_module.footerboxheader', verbose_name='سرتیتر مربوطه')),
            ],
            options={
                'verbose_name': 'آیتم',
                'verbose_name_plural': 'آیتم ها',
            },
        ),
    ]
