# Generated by Django 5.0.3 on 2024-04-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_module', '0005_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload-files/admin-uploads/banners', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'بنر',
                'verbose_name_plural': 'بنر ها',
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='banners',
            field=models.ManyToManyField(blank=True, null=True, to='site_module.sitebanner', verbose_name='بنرها'),
        ),
    ]
