# Generated by Django 5.0.3 on 2024-03-24 22:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(max_length=300, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='article_module.articlecategory', verbose_name='والد')),
            ],
            options={
                'verbose_name': 'دسته بندی مقالات',
                'verbose_name_plural': 'دسته بندی های مقالات',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='')),
                ('short_description', models.CharField(max_length=300, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
                ('is_active', models.BooleanField(default=True, verbose_name='')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='')),
                ('image', models.ImageField(upload_to='admin-uploads/article_images', verbose_name='')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='')),
                ('selected_categories', models.ManyToManyField(blank=True, null=True, to='article_module.articlecategory', verbose_name='')),
            ],
        ),
    ]
