# Generated by Django 5.0.3 on 2024-03-25 11:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0002_alter_article_options_alter_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='rate',
            field=models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='article',
            name='selected_categories',
            field=models.ManyToManyField(blank=True, to='article_module.articlecategory', verbose_name='دسته بندی های مربوطه'),
        ),
    ]
