# Generated by Django 5.0.3 on 2024-03-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_alter_article_rate_alter_article_selected_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='admin-uploads/article_images', verbose_name='تصویر'),
        ),
    ]
