# Generated by Django 5.0.3 on 2024-03-30 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_articlecomments_articlecommentsanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomments',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='article_module.article', verbose_name='مقاله مربوطه'),
        ),
    ]
