# Generated by Django 4.2.3 on 2024-03-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirm_code',
            field=models.CharField(max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, null=True, verbose_name='تلفن همراه'),
        ),
    ]
