# Generated by Django 4.2.3 on 2024-03-19 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0002_user_email_confirm_code_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
    ]
