# Generated by Django 4.2.3 on 2024-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_confirm_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
