# Generated by Django 4.2.3 on 2024-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, unique=True, verbose_name='آدرس ایمیل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_confirm_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='کد فعالسازی ایمیل'),
        ),
    ]
