# Generated by Django 5.0.3 on 2024-03-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acount_module', '0007_alter_user_email_alter_user_email_confirm_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_user_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن درباره کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload-files/admin-uploads/users_avater', verbose_name=''),
        ),
    ]
