# Generated by Django 4.2.3 on 2024-03-08 20:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=500, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی های محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=200, verbose_name='رنگ بندی محصول')),
                ('size', models.CharField(max_length=250, verbose_name='سایز محصول')),
            ],
            options={
                'verbose_name': 'اطلاعات محصول',
                'verbose_name_plural': 'کلیه اطلاعات محصولات',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('rate', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('enable', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='')),
                ('membership', models.CharField(choices=[('B', 'Beginner'), ('G', 'Gold'), ('S', 'Silver')], default='Beginner', max_length=1)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_module.productcategory', verbose_name='دسته بندی')),
                ('information', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop_module.productinformation', verbose_name='اطلاعات مربوطه')),
                ('tag', models.ManyToManyField(related_name='products', to='shop_module.tag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
