# Generated by Django 4.2.3 on 2024-03-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0004_alter_product_description_alter_product_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, null=True, verbose_name='جدید/قدیمی'),
        ),
    ]
