# Generated by Django 4.2.3 on 2024-03-10 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0005_product_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='جدید/قدیمی'),
        ),
    ]
