# Generated by Django 4.2.3 on 2024-03-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0006_alter_product_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان ایجاد'),
        ),
    ]
