# Generated by Django 4.2.3 on 2024-03-17 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0008_productbrand_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count_number_of_views',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تعداد مشاهده ها'),
        ),
    ]
