# Generated by Django 4.2.3 on 2024-03-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0010_product_last_watched_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(null=True, upload_to='uploads', verbose_name=''),
        ),
    ]
