# Generated by Django 4.2.3 on 2024-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0012_remove_product_file_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='admin-uploads/user-uploads')),
            ],
        ),
    ]
