# Generated by Django 4.2.3 on 2024-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_module', '0013_useruploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useruploadfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='user-uploads'),
        ),
    ]
