# Generated by Django 4.2.3 on 2024-03-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300, verbose_name='')),
                ('name', models.CharField(max_length=300, verbose_name='')),
                ('email', models.EmailField(max_length=300, verbose_name='')),
                ('text', models.TextField(verbose_name='')),
                ('is_read_by_admin', models.BooleanField(default=False, verbose_name='')),
                ('response', models.TextField(verbose_name='')),
            ],
        ),
    ]
