# Generated by Django 4.2.3 on 2024-03-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0002_alter_contactus_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='response',
            field=models.TextField(null=True, verbose_name='پاسخ'),
        ),
    ]
