# Generated by Django 4.2.3 on 2024-03-17 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_module', '0003_alter_contactus_response'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تیکت', 'verbose_name_plural': 'تیکت ها'},
        ),
    ]
